import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

export default [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is generated by Next and uses triple-slash references it
    // would fail its own rule on; the config files are legitimately anonymous
    // default exports.
    ignores: [
      '.next/**',
      'node_modules/**',
      'storybook-static/**',
      'next-env.d.ts',
    ],
  },
  {
    files: ['*.config.{mjs,ts}', '.storybook/**'],
    rules: { 'import/no-anonymous-default-export': 'off' },
  },
  {
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      /**
       * The design system has one source of truth: src/styles/design-tokens.css.
       *
       * A raw hex value in a component is how a palette drifts — six months on
       * there are four nearly-identical oranges and no way to change them
       * together. If a colour is needed that is not a token, the token file
       * changes first.
       */
      'no-restricted-syntax': [
        'error',
        {
          selector: 'Literal[value=/#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\\b/]',
          message:
            'No raw hex colours. Use a token from design-tokens.css (e.g. text-accent, bg-surface). Add a token if one is missing.',
        },
        {
          selector: 'TemplateElement[value.raw=/#(?:[0-9a-fA-F]{6})\\b/]',
          message:
            'No raw hex colours in template literals. Use a design token.',
        },
        {
          selector: 'Literal[value=/\\b(?:rgb|hsl)a?\\(/]',
          message:
            'No raw rgb()/hsl() colours. Use a token from design-tokens.css.',
        },
      ],
    },
  },
  {
    // The token file's own stories and the tokens module itself are exempt.
    files: ['src/styles/**', '**/*.stories.tsx'],
    rules: { 'no-restricted-syntax': 'off' },
  },
];
